# docker-compose.yml
version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: paymentdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: mypassword
    ports:
      - "5672:5672"
      - "15672:15672"

  ms-payment_service:
    build:
      context: ./ms-payment-service
    environment:
      DATABASE_URL: postgres://myuser:mypassword@postgres:5432/paymentdb
      RABBITMQ_URL: amqp://myuser:mypassword@rabbitmq:5672//
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8001:8000"

  ms-notification_service:
    build:
      context: ./ms-notification-service
    environment:
      RABBITMQ_URL: amqp://myuser:mypassword@rabbitmq:5672//
    depends_on:
      - rabbitmq
    ports:
      - "8002:8000"

volumes:
  postgres_data:

networks:
  rabbitmq_go_net: 
    driver: bridge
